theme = 'hugo-theme-relearn'
baseURL = 'https://cegepmv.github.io/420-113-MV'
languageCode = 'fr-fr'
title = "Système d'exploitation"
enableEmoji = true

[params]
    linkTitle = "Système d'exploitation"
    collapsibleMenu = true
    themeVariant = ['auto', 'zen-light', 'zen-dark', 'neon', 'learn']
    disableInlineCopyToClipBoard = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'